services:
  tasksdb:
    container_name: tasksdb
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: tasksdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  configserver:
    image: "davidbiagiola/configserver:s7"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  tasks:
    image: "davidbiagiola/tasks:s7"
    container_name: tasks-ms
    ports:
      - "9000:9000"
    environment:
      SPRING_APPLICATION_NAME: "tasks"
      SPRING_DATASOURCE_URL: "jdbc:mysql://tasksdb:3306/tasksdb"
    depends_on:
      tasksdb:
        condition: service_healthy
      configserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
  biagiolabank:
    driver: "bridge"