services:
  cardsdb:
    container_name: cardsdb
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: cardsdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  configserver:
    image: "davidbiagiola/configserver:s7"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

#  cards:
#    image: "davidbiagiola/cards:s7"
#    container_name: cards-ms
#    ports:
#      - "9000:9000"
#    environment:
#      SPRING_APPLICATION_NAME: "cards"
#      SPRING_DATASOURCE_URL: "jdbc:mysql://cardsdb:3306/cardsdb"
#    depends_on:
#      cardsdb:
#        condition: service_healthy
#      configserver:
#        condition: service_healthy
#    extends:
#      file: common-config.yml
#      service: microservice-configserver-config

networks:
  biagiolabank:
    driver: "bridge"